databases:
  - name: photo_app
    databaseName: photo_app
    user: photo_app
    region: singapore

services:
  - type: web
    name: photo_app
    env: ruby
    region: singapore
    plan: free
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec puma -C config/puma.rb'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: photo_app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
